### ISSUE TITLE
PyTorch-Lightning Incompatibility Issue  

### ISSUE THREAD

**Issue by denizkavi** [HySonLab/Protein_Redesign#2]
Creating the env from the yaml file makes it so that the versions of pytorch and pytorch lightning are incompatible, giving the error: `undefined symbol: iJIT_NotifyEvent`. I was able to manually edit to switch to pytorch 1.7.1, but that caused issues of its own. Sorry if a solution to this is in the works. 
```
Traceback (most recent call last):
  File "/home/ubuntu/Protein_Redesign/generate.py", line 11, in <module>
    import pytorch_lightning as pl
  File "/home/ubuntu/miniconda3/envs/ProteinReDiff/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ubuntu/miniconda3/envs/ProteinReDiff/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/ubuntu/miniconda3/envs/ProteinReDiff/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 21, in <module>
    from torch import Tensor
  File "/home/ubuntu/miniconda3/envs/ProteinReDiff/lib/python3.9/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/ubuntu/miniconda3/envs/ProteinReDiff/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

**Comment by chiragmathur27** [comment]
Hey Deniz,
Can you please tell me the versions of the pip dependencies you are using?

**Comment by denizkavi** [comment]
Was able to solve this specific error by switching to pytorch=1.12.1, but have a different issue afterwards

**Comment by chiragmathur27** [comment]
Can you tell me the python version you are using

**Comment by ndnng** [comment]
python used is 3.9, lightning is 1.7.7. 

 I installed torch via conda. Please check the environment file for versions.
